### ISSUE TITLE
NBT encoding

### ISSUE THREAD

**Issue by gentlegiantJGC** [pmmp/BedrockBlockPaletteArchive#1]
Are these files encoded with a custom NBT format?
It looks like the name and string length values are stored in a byte instead of 16 bits.
Are they varints?
I haven't seen this format before and our (Amulet) nbt parser can't open it.

**Comment by dktapps** [comment]
The format is described here: https://github.com/pmmp/BedrockBlockPaletteArchive#file-format

**Comment by gentlegiantJGC** [comment]
That doesn't mention that it is a custom NBT format other than a series of compound tags.
I did a little more digging and found the BedrockData readme that mentions it is a varint format like I thought. I assume this is a format you created since I haven't seen this anywhere else.

https://github.com/pmmp/BedrockData#canonical_block_statesnbt

**Comment by dktapps** [comment]
No, this is a format used by Bedrock on the wire. I exported it in this format since it was easiest to export from a BDS mod (requiring the fewest symbols to be reproduced - just `BinaryStream::writeTag()`). I could transcode them to some more standard format, but considering that my primary intent when creating this repo was to have a collection of palettes to feed back into said mods (for generation of blockstate mapping tables), it didn't make much sense.

If I find the time I may see if I can reproduce the symbols necessary to encode the palettes in standard Bedrock little-endian NBT instead, to make it easier for tools to use.

**Comment by gentlegiantJGC** [comment]
That would be useful. I should look into your tools as they would make it much easier to programmatically extract the data we need.
Up to now I have been using the private betas to generate the palette but that is only useful if the palette is the same as the full release.

**Comment by dktapps** [comment]
I recommend taking a look at this repository if you're interested in extracting this data from release binaries: https://github.com/pmmp/bds-mod-workspace

The tools in here work on both private partner builds and public release builds.

**Comment by dktapps** [comment]
I've updated the README with details on the format differences: https://github.com/pmmp/BedrockBlockPaletteArchive/commit/a445f4ad86f4e5267e1ed2465ec306ec78a3091d

**Comment by gentlegiantJGC** [comment]
thanks
